### ISSUE TITLE
help with wrapping a go lib?

### ISSUE THREAD

**Issue by sckott** [romainfrancois/gotest#2]
👋 @romainfrancois  trying to sort out how to wrap https://gitlab.com/gogna/gnparser/ in R. There is a grpc option, but that from my lack of experience as as equally hard to doing what you do here. Curious if you can give some tips on how I could get this to work. In main https://gitlab.com/gogna/gnparser/blob/master/gnparser/main.go he just calls this https://gitlab.com/gogna/gnparser/blob/master/gnparser/cmd/root.go - I'm not sure how I'd interact with it - definitely tried, but no dice yet

**Comment by romainfrancois** [comment]
It looks like this `main.go` makes an actual command line app. Typically when wrapping go code in R packages, I left the main() function empty, it just has to be there, and added other exported function in the main package (i.e. that start with an upper case letter), which in turn called another function from another go package. 

Most of what I know is in these slides: https://speakerdeck.com/romainfrancois/arrow-plus-ergo-1, or this video from useR: https://www.youtube.com/watch?v=b1JSq6LTPAQ

We meant to simplify the workflow, but this is dormant for now.

**Comment by sckott** [comment]
okay, thanks @romainfrancois
